### ISSUE TITLE
set_peer_down 是worker级别的行为，没看到同步到其他所有worker的逻辑？

### ISSUE THREAD

**Issue by xiewenhui** [upyun/lua-resty-checkups#1]
看了下说明，，只有一个worker做 health check， 然后调用 upstream.set_peer_down；
但是 set_peer_down 是worker级别的行为，没看到同步到其他所有worker的逻辑？   这是bug吧？

 https://github.com/openresty/lua-upstream-nginx-module#set_peer_down
Note that this method only changes the peer settings in the current Nginx worker process. You need to synchronize the changes across all the Nginx workers yourself if you want a server-wide change (for example, by means of ngx_lua's ngx.shared.DICT).

**Comment by yejingx** [comment]
Yes, it's a known issue, we will fix it ASAP.

**Comment by lhjay1** [comment]
@xiewenhui 还请继续指点，看看这样做是否解决楼主的提问。
