### ISSUE TITLE
os.time() 是否应该替换成 ngx.time

### ISSUE THREAD

**Issue by liuyangc3** [upyun/lua-resty-checkups#10]
in base.lua
```lua
local CHECKUP_TIMER_KEY = "checkups:timer:" .. os.time()
```

os.time 这个函数 老生常谈了，这里是否应该使用消耗更小的 ngx.time 更为合适？

**Comment by yejingx** [comment]
我想你指的是 `ngx.time` 吧？

1. `ngx.time` 不能在 `init` 阶段使用。
2. checkups 通常是在 `init_by_lua` 的时候被初始化的，并且只有一次，所以无所谓系统调用带来的性能损耗。

**Comment by liuyangc3** [comment]
谢谢，已修正

**Comment by liuyangc3** [comment]
点错了

**Comment by yejingx** [comment]
> 在 init_worker.lua 中也不能用么,我是在 init_worker.lua 看到的这个

也可以在 `init_worker` 中使用，我们这么做是为了通用性考虑。

之前因为 ngx_lua 的限制，`prepare_checker` 与 `create_checker` 都放在了 `init_worker` 里，现在我们一般会把 `prepare_checker` 放到 init 里。

**Comment by liuyangc3** [comment]
谢谢，目前还没看到 prepare_checker 这块，另外回复很快， 赞:+1:
