### ISSUE TITLE
一个节点发生宕机会堵塞其他其他节点的心跳检查

### ISSUE THREAD

**Issue by mapleincode** [upyun/lua-resty-checkups#11]
目前心跳检查是串行的。一旦一个节点发生宕机(关机)或者节点不存在，`SYN`在第一次请求失败之后，会重新以时间倍数增长的方式发起请求，直到请求时间达到一分钟，才会进入下个节点的心跳检测。一旦多台节点同时宕机或者配置了多个不存在的节点，就会堵塞`N * 60s`的时间，以至于影响其他机子的心跳检测。

**Comment by tokers** [comment]
@mapleincode 连接超时时间可以考虑设置的短一些

**Comment by mapleincode** [comment]
@tokers 好像并没有对应的参数可以设置。

**Comment by tokers** [comment]
@mapleincode 现在 checkups 已经支持并发的心跳检查了，见提交 https://github.com/upyun/lua-resty-checkups/commit/31fc860ab78c1b522c1ceb7b653e60d6c8d1885a 。

这个 issue 应该可以关闭了，@huangnauh。
