### ISSUE TITLE
round_robin轮训策略不均衡

### ISSUE THREAD

**Issue by congyewudi** [upyun/lua-resty-checkups#30]
默认是使用round_robin的，但是测试的时候发现，2台后端server，请求速率低的时候1个QPS 总是轮训到第一个，只有更高QSP的时候轮训交替正常。

**Comment by yejingx** [comment]
你的配置能提供下吗？按理说不会这样，测试代码里有测 rr 轮询的。

**Comment by congyewudi** [comment]
server {
    listen 8081;
    location = /12350 {
        proxy_pass http://127.0.0.1:12350/;
    }
    location = /12351 {
        proxy_pass http://127.0.0.1:12351/;
    }

    location = /t {
        content_by_lua_block {
            local checkups = require "resty.checkups.api"

            local callback = function(host, port)
            local res = ngx.location.capture("/" .. port)
                ngx.say(res.body)
                return 1
            end
            local ok, err
			
            ok, err = checkups.get_status()

            for k,v in pairs(ok) do
                if k == 'cls:ups2' then
                    ngx.say('ups2 is exist')
                else
                ok, err = checkups.update_upstream("ups2", {
                        {
                            servers = {
                                {host="127.0.0.1", port=12350, weight=10, max_fails=3, fail_timeout=10},
                                {host="127.0.0.1", port=12351, weight=10, max_fails=3, fail_timeout=10},
                            }
                        },
                    })
                if err then ngx.say(err) end
                end
            end

            ok, err = checkups.ready_ok("ups2", callback)
            if err then ngx.say(err) end
        }
    }
}

按照这个配置你测试下，希望尽快解决哦！这个东西很好用

**Comment by congyewudi** [comment]
sorry，我用错了，正常，整不好意思！
