### ISSUE TITLE
求教:lua-resty-checkups/lib/resty/checkups/api.lua:87: attempt to call field 'encode' (a nil value)

### ISSUE THREAD

**Issue by ttany** [upyun/lua-resty-checkups#43]
求教作者：
最近在研究这块的，在使用readme中第一个实例的时候，报了如下的错误：
![image](https://user-images.githubusercontent.com/26765476/50270089-6724fd80-046b-11e9-85ef-7652bd7c9b80.png)

我想数据应该是从config.lua中读取数据转成json时没有去到值，希望您给予帮助

**Comment by huangnauh** [comment]
依赖 cjson , 可以参考下 slardar 的 [Makefile](https://github.com/upyun/slardar/blob/master/Makefile#L115)

**Comment by ttany** [comment]
谢谢你能回复，刚刚那个是因为装到了系统全局的lua 库；现在遇到新问题了，如下：
![image](https://user-images.githubusercontent.com/26765476/50275099-9e021000-0479-11e9-963c-eabb0fc5b4ef.png)
